theme: jekyll-theme-cayman
<!DOCTYPE html> 
<html lang="en">
<head>
<meta charset="UTF-8">
<title>The Importance of Active Environmentalism</title>
<link rel="stylesheet" type="text/css" href="index.css">
</head>
<body>
	<h1 id="top">The Importance of Active Environmentalism</h1>
	<!-- id="top" for an internal link to go back to the top of the webpage -->
	<!-- div tags used to group elements together for styling purposes -->
        <div id="table-of-contents">
				<h2>Table of Contents</h2>
				<!--table of contents, along with relative links to their locations in the webpage -->
				<ol>
					<li>
						<a href="#brief">In Brief</a>
					</li>
					<li>
						<a href="#evidence">Evidence</a>
					</li>
					<li>
						<a href="#cause">Cause</a>
					</li>
					<li>
						<a href="#effect">Effect</a>
					</li>
					<li>
						<a href="#sleep-debt">Sleep Debt</a>
					</li>
					<li>
						<a href="#solutions">Solutions</a>
					</li>
					<li>
						<a href="#napping">Napping</a>
					</li>
				</ol>
			</div>
	</p>
	<h1 id="brief">In Brief</h1>
			<hr>
	     <h2 style="background-color:rgb(255,255,255);"> Climate change has already impacted our lives by rising sea levels and global warming, however it might not be too late to start a new revolution of getting rid of single use plastics and instead using biodegradable ones. Underneath I will briefly explain what is happening.</h2>
		 <hr>
    
			<p> The rapid deterioration of our planet is no longer a subtle suggestion for change. For many millennia, humans have contributed to climate change, and now it's our time to reverse it. With this crisis on our hands, I will be discussing what climate change is, its effects, its causes, and how we can work towards a better future. Climate change is the long-term alteration of temperature and typical weather patterns in a place, including global warming caused by man-made greenhouse gas emissions, with results such as large-scale shifts in weather patterns. Climate change causes frequent and intense heat waves, storms, droughts, rising sea levels, melting glaciers, and warming oceans. These natural disasters destroy animal habitats and wreak havoc on people's livelihoods and communities. It is estimated that globally, 50 billion tonnes of CO2 gets emitted into the atmosphere annually. This is 40% higher than emissions in 1990, which was around 35 billion tonnes. Some causes for rising emissions include burning oil, coal, and gas, deforestation, increased livestock farming, fertilizers containing nitrogen, and fluorinated gases. Firstly, burning coal, oil, and gas produce carbon dioxide and nitrous oxide. Next, deforestation is when trees are cut down and the beneficial effect is lost when the carbon stored in trees is released into the atmosphere. Thirdly, increased livestock farming is when cows and sheep produce large amounts of methane when they digest their foods. Fourthly, fertilizers containing nitrogen produce nitrous oxide emissions. Fifthly, fluorinated gases are emitted from equipment and products. Such emissions have a very strong warming effect, up to 23,000 times greater than CO2. Although many other factors add to climate change, greenhouse gas emissions are undoubtedly a leading cause of this crisis.
				There are many ways you can contribute to reversing the effects of climate change. This includes taking public transportation, walking, biking, not using single-use plastic, recycling, and prioritizing sustainability in your everyday life when possible. You can also focus on climate change when voting for parties that are actively contributing to environmental change.
			<p>
			<h1 style="background-color:#FFFFFF; color:black;">Evidence</h1>
			<p style="font-size:15px; background-color:rgb(255,255,255);"> Currently 19 of the hottest years have occured since the 200's, with the years 2016 & 2020 with the hottest year on record. This data was from the research that the 
			<a href="https://climate.nasa.gov/vital-signs/global-temperature/"> National Oceanic and Atmospheric Administration </a> have conducted since 1880.</p>
			<hr>
			<br>
			<h1 style="background-color:#FFFFFF; color:black;">Cause & Effect</h1>
			<p> Energy from Earth comes from the Sun after 50% of them filtering through the clouds and air in the Earth's atmosphere. After the remaining energy gets absorbed on the surface, it gets radiated as infrared heat where 90% of this gets absorbed by GreenHouse gasses. Some examples of GreenHouse Gasses are:
			<br>
			 <a href="https://climate.nasa.gov/causes/">
       <img src="https://climate.nasa.gov/system/internal_resources/details/original/249_Causes-greenhouse-gas-molecules-cropped-more-55.jpg" alt="Water Vapor, Methane, Nitrous Oxygen and Carbon Dioxide Molecules" width="600">
       </a>
	   <p> Some effects are; melting ice, sea levels rising, more heatwaves, changes in precipitation, more drought with stronger and more intense hurricanes. 
	</body>
	<div id="validators" class="background_color_fix">
			<a href="https://validator.w3.org/check?uri=https://">
				<img src="html_validator.png" alt="html5 validator" width="165">
			</a>
			<a href="https://jigsaw.w3.org/css-validator/validator?uri=https://tanjqy.github.io/home/">
				<img src="css_sheep.png" alt="W3schools css validator sheep" width="165">
			</a>
		</div>
	</html>
